### ISSUE TITLE
Spring function binding not working 

### ISSUE THREAD

**Issue by salman-khandu** [idealo/spring-cloud-stream-binder-sqs#37]
I have set up a spring cloud stream with sqs binder where there are two applications producer and consumer. Here my configuration

**1) Producer Application**

application.yml
```
spring:
  cloud:
    stream:
      bindings:
        sourceForBroker-out-0:
          destination: testqueue
      function:
        definition: sourceForBroker
```
Spring function

```
        @Bean
	public Supplier<Flux<Model>> sourceForBroker() {
		// push data in queue logic
	}
```

**2) Consumer Application** 

application.yml
```

spring:
  cloud:
    stream:
      bindings:
        req1:
          destination: testqueue
      function:
        bindings:
          consumer1-in-0: req1
        definition: consumer1
```
Spring function
```

       @Bean
	public Consumer<Model> consumer1() {
		return t-> System.out.println("id:" + t.getId());
	}
```

I have checked logs for producer application able push data in the queue as well as I have also check consumer logs and found that consumer application received messages that sent by producer application to testqueue but my function i.e consumer1(..) not getting those data.

**Comment by mKeRix** [comment]
So, the problem is that message sending and receiving works ok, but the message is not passed to your function bean correctly? How did you verify that the message was received correctly? And out of curiosity, does it work if you remove the manually set name (`req1`) and just reference `consumer1-in-0` in the stream bindings directly?

**Comment by salman-khandu** [comment]
I have checked aws HTTP call logs where the data which I producer put it there and it also send the call to delete the message.

I have checked by removing reqqq and using consumer1-in-0 directly in function binding itself like

```
spring:
  cloud:
    stream:
      bindings:
         consumer1-in-0:
          destination: testqueue
```
but the application doesn't fail to start.

**Comment by salman-khandu** [comment]
@mKeRix 

```
    stream:
      sqs:
        bindings:
          req1:
            consumer:
              snsFanout: false
      bindings:
        req1:
          destination: SQSForBrokerPerformanceTesting
          group: requester
      function:
        bindings:
          consumer1-in-0: req1
        definition: consumer1
```

I have put SQS binding with snsFanount: false. Now it's working to find also consumer<Model> consumer1() able to get those data.


```
  @Bean
	public Consumer<Model> consumer1() {
		return t-> System.out.println("id:" + t.getId());
	}
```


There is one more issue I see is consumer concurrency not working i.e 

```
 stream:
      sqs:
        bindings:
          req1:
            consumer:
              snsFanout: false
      bindings:
        req1:
          destination: SQSForBrokerPerformanceTesting
          group: requester
          consumer:
             concurrency: 5
      function:
        bindings:
          consumer1-in-0: req1
        definition: consumer1
```
