### ISSUE TITLE
waitTimeout doesn't do anything

### ISSUE THREAD

**Issue by keinh** [idealo/spring-cloud-stream-binder-sqs#86]
Hello, I'm trying to build an app that uses AWS SQS / SNS / S3. But I'm running into an issue where the wait timeout isn't configurable

Here's a simple explanation of my application:

application.yaml
```
spring:
  main:
    # necessary to override some cloud-aws beans with those from cloud-stream-binder-sqs
    allow-bean-definition-overriding: true
  cloud:
    stream:
      default-binder: sqs
      sqs:
        bindings:
          someFunc-in-0:
            # configuration for the cloud stream sqs consumer
            consumer:
              snsFanout: true
              visibilityTimeout: 10
              waitTimeout: 10
              maxNumberOfMessages: 10
      bindings:
        someFunc-in-0:
          # incoming sqs queue listens to outgoingSnsTopic
          destination: incoming
          binder: sqs
          consumer:
            concurrency: 10
        sendRequest-out-0:
          destination: outgoingSnsTopic
          binder: sns
```

Stream.java
```
  @Scheduled(fixedDelay = 4000) 
  public boolean sendRequest() {
    return this.streamBridge.send("sendRequest-out-0", UUID.randomUUID());
  }

 @Bean
 public Consumer<Object> someFunc() {
    return response -> {
      logger.info("---------- Received Message -------------");
      logger.info(response);
      return;
    };
```

With a wait timeout of 10, and messages being send every 4s,I would expect the Consumer bean from someFunc() to be triggered 2-3 times every 10 seconds, but as of now the Consumer bean gets triggered quickly after a message is sent from sendRequest() 
Did I miss configure something somehow? The example you have on the RAEDME is pretty straightforward. Or is it an issue with the bean overriding being set to true? I can't get the app to start without it since I need the S3 connection.
